export const products = [
  {
    id: 1,    
    name: "Produto 1",
    description: "Descrição do Produto 1",
    detailedDescription: "lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum",
    price: 49.99,
    image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 2,    
    name: "Produto 2",
    description: "Descrição do Produto 2",
    detailedDescription: "lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum",
    price: 59.99,
    image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 3,    
    name: "Produto 3",
    description: "Descrição do Produto 3",
    detailedDescription: "lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum",
    price: 69.99,
    image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 4,    
    name: "Produto 4",
    description: "Descrição do Produto 4",
    detailedDescription: "lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum",
    price: 79.99,
    image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 5,    
    name: "Produto 5",
    description: "Descrição do Produto 5",
    detailedDescription: "lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum",
    price: 89.99,
    image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 6,    
    name: "Produto 6",
    description: "Descrição do Produto 6",
    detailedDescription: "lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum",
    price: 99.99,
    image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 7,    
    name: "Produto 7",
    description: "Descrição do Produto 7",
    detailedDescription: "lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum",
    price: 109.99,
    image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 8,    
    name: "Produto 8",
    description: "Descrição do Produto 8",
    detailedDescription: "lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum",
    price: 119.99,
    image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 9,    
    name: "Produto 9",
    description: "Descrição do Produto 9",
    detailedDescription: "lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum",
    price: 129.99,
    image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 10,    
    name: "Produto 10",
    description: "Descrição do Produto 10",
    detailedDescription: "lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum",
    price: 139.99,
    image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 11,    
    name: "Produto 11",
    description: "Descrição do Produto 11",
    detailedDescription: "lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum",
    price: 149.99,
    image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 12,    
    name: "Produto 12",
    description: "Descrição do Produto 12",
    detailedDescription: "lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum dolor sit amet lorem ipsum dolor amet lorem ipsum",
    price: 159.99,
    image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
];
